pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: false
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - Messaging.Core

variables:
  buildConfiguration: 'Release'
  NuGetFeed: 'Pesto' 
  Directory: 'Messaging.Core'
  PackagesToPack: '$(Directory)/Messaging.Core.csproj'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: '$(PackagesToPack)'
      workingDirectory: '$(Directory)'
  - task: DotNetCoreCLI@2
    displayName: "Pack"
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: '$(PackagesToPack)'
      nobuild: true
      versioningScheme: 'off'
      workingDirectory: '$(Directory)'
  - task: NuGetAuthenticate@0
    displayName: 'Authenticate'
  - task: NuGetCommand@2
    displayName: 'Push'
    inputs:
      command: push
      publishVstsFeed: '$(NuGetFeed)'
      allowPackageConflicts: true
      workingDirectory: '$(Directory)'